function buildGUI(obj)
    %creata GUI Figure
    obj.fig = uifigure('Name','Serialinterface - PPG Simulator',...
             'Position', [100 100 950 400]);

    obj.signalFileListing = dir('signaldata/*.mat');     

    % set callback for closerequest
    figure = obj.fig;
    figure.CloseRequestFcn = @(figure,event)obj.my_closereq();

    obj.dd_selPort = uidropdown(obj.fig,...
            'Position',[10 350 100 25],...
            'Items', seriallist('available'),...
            'DropDownOpeningFcn', @obj.evt_dd_portSelectCBF);

    obj.dd_selBAUD = uidropdown(obj.fig,...
            'Position',[120 350 100 25],...
            'Items', {'9600', '57600', '115200'},...
            'ItemsData', [9600, 57600, 115200]);

    obj.dd_showASCII = uidropdown(obj.fig,...
            'Position',[10,315,100,25],...
            'Items', {'DEC', 'HEX', 'ASCII'},...
            'ItemsData', [1, 2, 3]);

    obj.dd_headerByte = uidropdown(obj.fig,...
            'Position',[230,315,100,25],...
            'Items', {'None', 'CTRL_Byte', 'DATA_Byte', 'ERR_Byte'},...
            'ItemsData', [0x00, 0x11, 0x12,0x13]);

    obj.btn_clearScreen = uibutton(obj.fig,...
            'Position',[120,315,100,25],...
            'Text','Clear',...
            'ButtonPushedFcn', @obj.evt_btn_clearScreenCBF);

    obj.btn_cnnctPort = uibutton(obj.fig,...
            'Position',[230,350,100,25],...
            'Text','Connect',...
            'ButtonPushedFcn', @obj.evt_btn_connectSerialCBF);

    obj.btn_dscnnctPort = uibutton(obj.fig,...
            'Position',[340,350,100,25],...
            'Text','Disconnect',...
            'Enable',0,...
            'ButtonPushedFcn', @obj.evt_btn_disconnectSerialCBF);

    obj.cb_showSend = uicheckbox(obj.fig,...
            'Position',[520,315,150,25],...
            'Text','show Send Data',...
            'Value',0);                               

    obj.txa_outputWindow = uitextarea(obj.fig,...
            'Position',[10, 50, 440, 250],...
            'ValueChangedFcn', @(~,~) (txa_outScrollBtm(obj)));

    obj.txa_inputForm = uieditfield(obj.fig,'text',...
            'Position', [10,10,330,25],...
            'ValueChangedFcn', @obj.evt_btn_sendMsgCBF);            

    obj.btn_sendMsg = uibutton(obj.fig,...
            'Position',[350,10,100,25],...
            'Text','Send',...
            'Enable',0,...
            'ButtonPushedFcn', @obj.evt_btn_sendMsgCBF);

    obj.btn_sendData = uibutton(obj.fig,...
            'Position',[520,350,100,25],...
            'Text','Send Data',...
            'Enable',0,...
            'ButtonPushedFcn', @obj.evt_btn_sendDateCBF);

    obj.dd_selSignalFile = uidropdown(obj.fig,...
            'Position',[630 350 200 25],...
            'Items', {obj.signalFileListing.name});

    obj.ax_plot = uiaxes(obj.fig,...
            'Position', [500,50,440,250]);

end
